#!/bin/bash
# .bash_profile

# Source .bashrc if it exists
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# Terminal Settings
export TERM=xterm-256color

 export PATH="$PATH:$HOME/workspace/github.com/oven-sh/bun/build"


# Check for Homebrew path on Apple Silicon-based Macs
# On Apple Silicon Macs, Homebrew is typically installed at `/opt/homebrew/bin/brew`.
if [ -f "/opt/homebrew/bin/brew" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"

# Check for Homebrew path on Intel-based Macs
# On Intel Macs, Homebrew is typically installed at `/usr/local/bin/brew`.
elif [ -f "/usr/local/bin/brew" ]; then
    eval "$(/usr/local/bin/brew shellenv)"

# Error message if Homebrew is not found
# If Homebrew is not found in either of the above paths, display an error message.
else
    echo "Homebrew is not installed."
fi

export PATH="/usr/local/opt/llvm@16/bin:$PATH"

# Load local settings if available
if [ -f $HOME/.bashrc.d/bash_local ]; then
    . $HOME/.bashrc.d/bash_local
fi

# neovim as man viewer, if available
if command -v nvim &> /dev/null; then
    export MANPAGER='nvim +Man!'
fi

export PATH="$HOME/.local/bin:$PATH"

# Initialize version managers
# anyenv
if command -v anyenv &> /dev/null; then
    eval "$(anyenv init -)"
fi

# Language-specific environment setups
# Go
if [ -d /usr/local/go ]; then
    export PATH="/usr/local/go/bin:$PATH"
fi

if [ -d ~/go ]; then
    export GOBIN=$HOME/go/bin
    export GOPATH=$HOME/go

    export PATH="$HOME/go/bin:$PATH"
fi

# Haskell
[ -f "/Users/yutanakamura/.ghcup/env" ] && source "/Users/yutanakamura/.ghcup/env" # ghcup-env

# Android Studio
export PATH="$PATH:$HOME/Library/Android/sdk/platform-tools"

# Volta
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH=$BUN_INSTALL/bin:$PATH

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# pnpm
export PNPM_HOME="/Users/yutanakamura/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end


# rust
if [ -f "$HOME/.cargo/env" ]; then
    . "$HOME/.cargo/env"
fi

# Conditional behavior for VSCode terminal
if [ "$TERM_PROGRAM" != "vscode" ]; then
    # auto start tmux if available
    if command -v tmux &> /dev/null; then
        . $HOME/.bashrc.d/auto_start_tmux.sh
    fi

    # switch to fish shell if available
    if command -v fish &> /dev/null; then
        exec fish
    fi
fi
# Lines below this will not execute when using fish shell
