#!/bin/bash

set -u

# Define the base directory where the setup directories are located
INSTALL_DIR="./installers"

# Function to list all available software setups
list_tools() {
    echo "Available installers:"
    for installer in "${INSTALLERS[@]}"; do
        echo "- $installer"
    done
}

# Function to setup a specific tool
install() {
    local tool_name="$1"
    echo "Setting up $tool_name..."

    local tool_setup_script="${INSTALL_DIR}/${tool_name}.sh"


    # Check if the tool-specific setup script exists and is executable
    if [[ -x "$tool_setup_script" ]]; then
        ./$tool_setup_script
        echo "$tool_name install complete."
    else
        echo "No setup script found for $tool_name, skipping..."
    fi
}

# List of supported tools (script within installers/)
INSTALLERS=($(find $INSTALL_DIR -type f -name "*.sh"  | xargs -n1 basename | sed 's/.sh//'))

# Parse command line arguments
if [ "$#" -eq 0 ]; then
    echo "Usage: ./install [TARGET|-a|-l]"
    exit 1
elif [ "$1" == "-l" ]; then
    list_tools
    exit 0
elif [ "$1" == "-a" ]; then
    # Install and setup all tools
    for tool in "${INSTALLERS[@]}"; do
        install "$tool"
    done
else
    TOOL_TO_INSTALL=$1
    if [[ " ${INSTALLERS[@]} " =~ " ${TOOL_TO_INSTALL} " ]]; then
        install "$TOOL_TO_INSTALL"
    else
        echo "Unsupported or unknown tool: $TOOL_TO_INSTALL. Use '-l' to list all available software installers."
        exit 1
    fi
fi
