#!/bin/bash

set -u

# Define the base directory where the setup directories are located
SETUP_DIR="./setups"

# Function to list all available software setups
list_tools() {
    echo "Available software setups:"
    for tool in "${TOOLS[@]}"; do
        echo "- $tool"
    done
}

# Function to setup a specific tool
setup_tool() {
    local tool_name="$1"
    echo "Setting up $tool_name..."

    local tool_setup_dir="$SETUP_DIR/$tool_name"
    local tool_setup_script="$tool_setup_dir/setup.sh"

    # Check if the tool-specific setup script exists and is executable
    if [[ -x "$tool_setup_script" ]]; then
        # Execute the tool-specific setup script
        (cd "$tool_setup_dir" && "./setup.sh")
        echo "$tool_name setup complete."
    else
        echo "No setup script found for $tool_name, skipping..."
    fi
}

# List of supported tools (directories within setups/)
TOOLS=($(ls -1 $SETUP_DIR))

# Parse command line arguments
if [ "$#" -eq 0 ]; then
    echo "Usage: ./setup [TARGET|-a|-l]"
    exit 1
elif [ "$1" == "-l" ]; then
    list_tools
    exit 0
elif [ "$1" == "-a" ]; then
    # Install and setup all tools
    for tool in "${TOOLS[@]}"; do
        setup_tool "$tool"
    done
else
    TOOL_TO_SETUP=$1
    if [[ " ${TOOLS[@]} " =~ " ${TOOL_TO_SETUP} " ]]; then
        setup_tool "$TOOL_TO_SETUP"
    else
        echo "Unsupported or unknown tool: $TOOL_TO_SETUP. Use '-l' to list all available software setups."
        exit 1
    fi
fi
