# Essential Plugins
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = "make"
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = "Shougo/vimshell"


#General Use
[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'tpope/vim-fugitive' #git client
[[plugins]]
repo = 'mileszs/ack.vim'
[[plugins]]
repo = 'rhysd/accelerated-jk'


# Editor UI
[[plugins]]
repo = 'itchyny/lightline.vim' #status line
[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'


# ColorSchemes
[[plugins]]
repo = "KeitaNakamura/neodark.vim"
[[plugins]]
repo = "tomasr/molokai"


# static analysis
[[plugins]]
repo = 'w0rp/ale'


# Language Specific
#
# HTML
[[plugins]]
repo ='othree/html5.vim'
[[plugins]]
repo = 'mattn/emmet-vim'
[[plugins]]
repo = 'slim-template/vim-slim'


# css
[[plugins]]
repo = 'othree/csscomplete.vim'


# javascript
[[plugins]]
repo = 'posva/vim-vue'


# toml
[[plugins]]
repo = 'cespare/vim-toml'
