# Essential Plugins
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = "make"
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = "Shougo/vimshell"


#General Use
[[plugins]]
repo = 'junegunn/fzf.vim' #fuzzy search
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'tpope/vim-fugitive' #git client
[[plugins]]
repo = 'rhysd/accelerated-jk'
[[plugins]]
repo = 'scrooloose/nerdcommenter'

# Editor UI
[[plugins]]
repo = 'itchyny/lightline.vim' #status line
[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'


# ColorSchemes
[[plugins]]
repo = "KeitaNakamura/neodark.vim"
[[plugins]]
repo = "tomasr/molokai"


# Completion
[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = '''has('lua')'''
[[plugins]]
repo = 'Shougo/neocomplcache.vim'
if = '''!has('lua')'''
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'


# Language Specific
#
# HTML
[[plugins]]
repo ='othree/html5.vim'
[[plugins]]
repo = 'mattn/emmet-vim'
[[plugins]]
repo = 'slim-template/vim-slim'


# css
[[plugins]]
repo = 'othree/csscomplete.vim'


# javascript
[[plugins]]
repo = 'othree/yajs.vim' #hight for ES6 Syntax
[[plugins]]
repo = 'ternjs/tern_for_vim'
build = 'npm install'
[[plugins]]
repo = 'posva/vim-vue'


# Ruby, Ruby on Rails
[[plugins]]
repo = 'yuku-t/vim-ref-ri'
[[plugins]]
repo = 'tpope/vim-rails'
[[plugins]]
repo = 'basyura/unite-rails'


# Python
[[plugins]]
repo = 'davidhalter/jedi-vim'


# fish
[[plugins]]
repo = 'dag/vim-fish.git' #fish highting


# toml
[[plugins]]
repo = 'cespare/vim-toml'


# VimScript
[[plugins]]
repo = 'Shougo/neco-vim'
