# Essential Plugins
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = "make"
[[plugins]]
repo = "Shougo/vimshell"


#General Use
[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'tpope/vim-fugitive' #git client
[[plugins]]
repo = 'mileszs/ack.vim'
[[plugins]]
repo = 'rhysd/accelerated-jk'
[[plugins]]
repo = 'junegunn/fzf.vim' #fuzzy search
[[plugins]]
repo = 'Shougo/neco-syntax'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'easymotion/vim-easymotion'

# Editor UI
[[plugins]]
repo = 'itchyny/lightline.vim' #status line
[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
[[plugins]]
repo = 'scrooloose/nerdtree'


# ColorSchemes
[[plugins]]
repo = "KeitaNakamura/neodark.vim"
[[plugins]]
repo = "tomasr/molokai"
# [[plugins]]
# repo = "chriskempson/base16-vim"
# if = '''has('nvim')'''


# rainbow parentheses
[[plugins]]
repo = "kien/rainbow_parentheses.vim"


# gtags
[[plugins]]
repo = 'lighttiger2505/gtags.vim'


# static analysis
[[plugins]]
repo = 'w0rp/ale'


# Language Specific
#
# HTML
[[plugins]]
repo ='othree/html5.vim'
[[plugins]]
repo = 'mattn/emmet-vim'
[[plugins]]
repo = 'slim-template/vim-slim'


# css
[[plugins]]
repo = 'othree/csscomplete.vim'


# javascript
[[plugins]]
repo = 'posva/vim-vue'
[[plugins]]
repo = 'carlitux/deoplete-ternjs' # JS completion
[[plugins]]
repo = 'digitaltoad/vim-pug' # JS syntax highlight


# Racket
[[plugins]]
repo = 'wlangstroth/vim-racket'


# toml
[[plugins]]
repo = 'cespare/vim-toml'
