# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: lambdalisue/neovim-ci:v0.4.2
    steps:
      - checkout
      - run: ls
      - run: pwd
      - run: /bin/bash install.sh
