#!/bin/bash
# .bash_profile

# Source .bashrc if it exists
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# Terminal Settings
export TERM=xterm-256color

# Homebrew
eval "$(/usr/local/bin/brew shellenv)"

# Load local settings if available
if [ -f $HOME/.bashrc.d/bash_local ]; then
    . $HOME/.bashrc.d/bash_local
fi

# neovim as man viewer, if available
if command -v nvim &> /dev/null; then
    export MANPAGER='nvim +Man!'
fi

# Initialize version managers
# anyenv
if command -v anyenv &> /dev/null; then
    eval "$(anyenv init -)"
fi

# Language-specific environment setups
# Go
if [ -d /usr/local/go ]; then
    export PATH="/usr/local/go/bin:$PATH"
fi

if [ -d ~/go ]; then
    export PATH="~/go/bin:$PATH"
fi

# Haskell
[ -f "/Users/yutanakamura/.ghcup/env" ] && source "/Users/yutanakamura/.ghcup/env" # ghcup-env

# Android Studio
export PATH="$PATH:$HOME/Library/Android/sdk/platform-tools"

# Volta
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# Conditional behavior for VSCode terminal
if [ "$TERM_PROGRAM" != "vscode" ]; then
    # auto start tmux if available
    if command -v tmux &> /dev/null; then
        . $HOME/.bashrc.d/auto_start_tmux.sh
    fi

    # switch to fish shell if available
    if command -v fish &> /dev/null; then
        exec fish
    fi
fi
# Lines below this will not execute when using fish shell


