#!/bin/bash
# .bash_profile

# Get aliases and functions
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

DOTFILES="$HOME/dotfiles"


# Read local settings
if [ -f $DOTFILES/rc/bashrc.d/bash_local ]; then
  . $DOTFILES/rc/bashrc.d/bash_local
fi


# User specific environment and startup programs
export PATH="$HOME/local/script:$HOME/local/bin:$HOME/.local/bin:$PATH"
export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

TERM=xterm-256color

# use nvim as man viewer when available
if command -v nvim &> /dev/null; then
  export MANPAGER='nvim +Man!'
fi


if [ -d ~/.node_modules_global ]; then
  export PATH="$PATH:$HOME/.node_modules_global/bin"
fi

if command -v anyenv &> /dev/null; then
  eval "$(anyenv init -)"
fi


if [ -d ~/.pyenv ]; then
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

if [ -d /usr/local/go ]; then
  export PATH="/usr/local/go/bin:$PATH"
fi

if [ -d ~/go ]; then
  export PATH="~/go/bin:$PATH"
fi


if [ -d ~/.rbenv ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

if [ -d ~/.ndenv ]; then
  export PATH="$HOME/.ndenv/bin:$PATH"
  eval "$(ndenv init -)"
fi

if [ -d ~/.nodenv ]; then
  export PATH="$HOME/.nodenv/bin:$PATH"
  eval "$(nodenv init -)"
fi

if [ -d ~/.yarn ]; then
  export PATH="$HOME/.yarn/bin:$PATH"
fi

if [ -d /home/python/2.7/bin ]; then
  export PATH="$PATH:/home/python/2.7/bin"
fi


if [ -d /home/python/3.5/bin ]; then
  export PATH="$PATH:/home/python/3.5/bin"
fi

if [ -d $HOME/racket/bin ]; then
  export PATH="$PATH:$HOME/racket/bin"
fi

if [ -d $HOME/go/bin ]; then
  export PATH="$PATH:$HOME/go/bin"
fi

if [ -d $HOME/go/bin ]; then
  export PATH="$PATH:$HOME/go/bin"
fi

export PATH="$PATH:$HOME/Library/Android/sdk/platform-tools"

# auto start tmux
if command -v tmux &> /dev/null; then
. $DOTFILES/rc/bashrc.d/auto_start_tmux.sh
fi

# use fish when available
if command -v fish &> /dev/null; then
  exec fish
fi
### LINE BELOW THIS LINE WILL NOT BE EXCUTED WHEN USING FISH SHELL
