" Esesntial Settings
set nocompatible
syntax enable

" load settings
runtime! init/basic.vim
runtime! init/mapping.vim
runtime! init/window.vim
runtime! ftplugin/man.vim
runtime! init/vim-plug.vim

" load colorscheme settings
runtime! init/color.vim

" terminal customize
" NOTE: Should be loaded after init/color.vim
runtime! init/terminal.vim

" load plugin settings
runtime! init/plugins/**/*.vim

if has('nvim-0.5')
  runtime! init/plugins/**/*.lua
endif

set omnifunc=v:lua.vim.lsp.omnifunc


" This must be written at the bottom of .vimrc
filetype indent plugin on
