#General Use
[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1
[[plugins]]
repo = 'scrooloose/nerdcommenter'
on_i = 1

# javascript
[[plugins]]
repo = 'othree/yajs.vim' #hight for ES6 Syntax
on_ft = ['javascript']

# Vue.js
[[plugins]]
repo = 'posva/vim-vue' #hight for vue.js
on_ft = ['vue']

# fish
[[plugins]]
repo = 'dag/vim-fish.git' #fish highting
on_ft = ['fish']

# Scheme
[[plugins]]
repo = 'aharisu/vim_goshrepl'
on_ft = ['scheme']
