#General Use
[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1
[[plugins]]
repo = 'scrooloose/nerdcommenter'
on_i = 1


# Completion
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = '''has('nvim') && has('python3')'''
hook_post_source = '''
" Use smartcase.
call deoplete#enable()
call deoplete#custom#option('smart_case', v:true)
'''
on_event = ['FocusLost', 'CursorHold', 'CursorHoldI', 'InsertLeave']

[[plugins]]
repo = 'Shougo/deoplete-lsp'
if = '''has('nvim') && has('python3')'''
on_event = ['FocusLost', 'CursorHold', 'CursorHoldI', 'InsertLeave']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = '''!has('nvim') && has('lua')'''
on_i = 1
[[plugins]]
repo = 'Shougo/neocomplcache.vim'
if = '''!has('lua') && !has('nvim')'''
on_i = 1
[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1


# javascript
[[plugins]]
repo = 'othree/yajs.vim' #hight for ES6 Syntax
on_ft = ['javascript']

# Vue.js
[[plugins]]
repo = 'posva/vim-vue' #hight for vue.js
on_ft = ['vue']

# Ruby, Ruby on Rails
[[plugins]]
repo = 'yuku-t/vim-ref-ri'
on_ft = ['ruby']
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

# fish
[[plugins]]
repo = 'dag/vim-fish.git' #fish highting
on_ft = ['fish']

# VimScript
[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim']

# Scheme
[[plugins]]
repo = 'aharisu/vim_goshrepl'
on_ft = ['scheme']
