name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the installer (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo ./install.sh

      - name: Run the installer (macOS)
        if: matrix.os == 'macos-latest'
        run: ./install.sh

      - name: Run test script
        run: ./test/test.sh
